import TransitionProvider from "./TransitionProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WebSite-MoSalah",
  description: `Generated by Mohamed Salah`,
  manifest: "/manifest.webmanifest",
  icons: { apple: "/icon.png" },
  themeColor: "#333",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" overflow-hidden">
          <TransitionProvider>{children}</TransitionProvider>
        </main>
      </body>
    </html>
  );
}
